USE QuanLyKhuVuiChoi
GO
ALTER TABLE dbo.DichVu DROP CONSTRAINT FK__DichVu__Ma_Khu__22AA2996
ALTER TABLE dbo.DichVu DROP COLUMN Ma_Khu

ALTER TABLE dbo.ThietBi DROP CONSTRAINT FK__ThietBi__Ma_TroC__1FCDBCEB
ALTER TABLE dbo.ThietBi DROP COLUMN Ma_TroChoi

CREATE TABLE ChiTietDV (
MaDV VARCHAR(10) REFERENCES dbo.DichVu(Ma_DV),
MaKhu VARCHAR(10) REFERENCES dbo.KhuVuc(Ma_Khu),
Gio_Mo TIME,
Gio_Dong TIME
)
CREATE TABLE ChiTietThietBi (
MaTC VARCHAR(10) REFERENCES dbo.TroChoi(Ma_TroChoi),
MaTB VARCHAR(10) REFERENCES dbo.ThietBi(Ma_TB),
SoLuong INT
)